
version: '3.8'

services:
  qdrant-db:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage

  neo4j-db:
    image: neo4j:5.20.0
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/demodemo
    volumes:
      - ./neo4j_data:/data

volumes:
  qdrant_data:
  neo4j_data:
